### ISSUE TITLE
qemu tcg fatal error

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#214]
Job hanging until aborted / timed out:
- http://build.ros.org/view/Queue/job/Jbin_arm_uThf__collada_urdf_jsk_patch__ubuntu_trusty_armhf__binary/2/console 
- http://build.ros.org/view/Queue/job/Jbin_arm_uThf__collada_urdf_jsk_patch__ubuntu_trusty_armhf__binary/3/console**

**Comment by tfoote** [comment]
I just saw this again today: http://build.ros.org/view/Queue/job/Kbin_arm_uXhf__astra_camera__ubuntu_xenial_armhf__binary/2/console

```
[  8%] Built target astra_camera_generate_messages_cpp
/usr/bin/make -f CMakeFiles/astra_openni2.dir/build.make CMakeFiles/astra_openni2.dir/depend
make[4]: Entering directory '/tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf'
cd /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5 /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5 /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf/CMakeFiles/astra_openni2.dir/DependInfo.cmake --color=
make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf'
/usr/bin/make -f CMakeFiles/astra_openni2.dir/build.make CMakeFiles/astra_openni2.dir/build
make[4]: Entering directory '/tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf'
[ 10%] Performing update step for 'astra_openni2'
cd /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf/astra_openni2/src/astra_openni2 && /usr/bin/cmake -P /tmp/binarydeb/ros-kinetic-astra-camera-0.1.5/obj-arm-linux-gnueabihf/astra_openni2/tmp/astra_openni2-gitupdate.cmake
/build/qemu-_D3HGx/qemu-2.0.0+dfsg/tcg/tcg.c:179: tcg fatal error
```

A little bit of reading suggests that it's a known intermittent bug upstream: 
https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1350435

This thread suggests that it might actually be out of RAM: https://github.com/ev3dev/ev3dev/issues/571

I know that this package does not compile successfully on the DB410c(1GB) w/o swap enabled. So if the machine was heavily loaded that might have caused the problem. If so it would connect to #271

**Comment by tfoote** [comment]
There were a couple of jobs that hung today. I saw a slightly different error, but again the job hung. http://build.ros.org:8080/job/Kbin_uxhf_uXhf__topic_tools__ubuntu_xenial_armhf__binary/16/console

There were these errors
```
qemu: Unsupported syscall: 384
qemu: Unsupported syscall: 384
qemu: Unsupported syscall: 384
qemu: Unsupported syscall: 384
```
And found this similar discussion: https://users.rust-lang.org/t/missing-system-calls-when-running-tests-under-qemu-arm-at-travisci/5013 suggesting it's a call to getrandom


Though [this FAQ](https://docs.resin.io/troubleshooting/troubleshooting/) says that most processes fall back to using `/dev/urandom` if the system call fails.

The above errors were not quite at the bottom so maybe they aren't actually the error. 

There's also a generic cmake qemu hang bug which was fixed recently in qemu 2.7: https://bugs.launchpad.net/qemu/+bug/955379  From the comments this will also fix git.

**Comment by Alabate** [comment]
I don't know if you're still interested in fixing this problem, but at least it can be useful for people having this problem and falling here because of google.

We had the same problem while working on a private build server for ros kinetic packages with qemu arm emulation. The build hang with theses lines as last output.
```
qemu: Unsupported syscall: 384
qemu: Unsupported syscall: 384
qemu: Unsupported syscall: 384
```
But after we retry with the same configuration, it still print theses lines, but don't hang.

This page: https://patchwork.openembedded.org/patch/115397/ suggest that hang could happened because of missing entropy which can be fixed by installing `rng-tools` in the arm image. I don't really know if it work, because this hang happened randomly, but if I don't edit this post, you can assume it worked.

**Comment by dirk-thomas** [comment]
@Alabate That sounds interesting. Can you please provide a patch which installs that package for arm jobs. It shouldn't do any harm and at best fixes the problem.

**Comment by dirk-thomas** [comment]
@Alabate any news on this?

**Comment by Alabate** [comment]
Sorry I didn't provide a patch because I didn't find which file to edit.
Anyways, this fix doesn't seem to work for us, arm build still hangs randomly for all ros distributions.

**Comment by dirk-thomas** [comment]
Just for the record: this is still happening frequently, e.g. http://build.ros.org/view/Queue/job/Kbin_uxhf_uXhf__libconcorde_tsp_solver__ubuntu_xenial_armhf__binary/112/console

Maybe we can try to install a newer version of `qemu` and see if it fixes the problem?

**Comment by nuclearsandwich** [comment]
Going to try and look at this later in the week and see how straightforward it would be to incorporate an updated qemu.

**Comment by tfoote** [comment]
Another failure type possiblly related: https://github.com/orocos/rtt_ros_integration/issues/95

**Comment by nuclearsandwich** [comment]
Over the last several weeks I have been running a few hosts on the buildfarm outfitted with  qemu-user-static 2.10+dfsg-0ubuntu3.1. The buildfarm was not terribly busy during this time period so while there was a lower apparent incidence of hanging arm jobs there was no significant reduction in hanging jobs and the updated hosts still had hangs.

While investigating a specific host I noticed that within the docker image the qemu-aarch64-staic binary inside the container image is still running qemu 2.1.93.

 Raising that with @tfoote he pointed me to the https://github.com/osrf/multiarch-docker-image-generation repo where the copies of these static binaries are sourced from.
I've opened a PR there (https://github.com/osrf/multiarch-docker-image-generation/pull/14) to try updated static binaries within the containers.

**Comment by nuclearsandwich** [comment]
Docker images updated to qemu 2.10 were pushed 8 days ago.

In that time, I've not observed or restarted any stuck qemu builds. @mikaelarguedas (I know we just talked offline, but for posterity), @dirk-thomas, @tfoote have any of you had to restart a build that was stuck in the last 8 days? If you do see one that's stuck in the coming build cycle can you send it to me before restarting it so I can investigate?

**Comment by mikaelarguedas** [comment]
I rebuild actionlib and all its deps on Kinertic and Lunar without noticing any job hung in CMake.
Though that was over the weekend so I didnt monitor closely

**Comment by tfoote** [comment]
I haven't noticed any hanging builds but also haven't been watching closely. Browsing through the histories of the recent arm builds I haven't found a hung build in that time period either.

**Comment by nuclearsandwich** [comment]
I've been checking the at least farm once daily since this change was deployed. It hasn't been the most active two weeks but it also hasn't been inactive and the fact that none of us have seen a hung build in that time gives me hope that this issue is resolved.

I'm going to close this ticket as having been addressed by https://github.com/osrf/multiarch-docker-image-generation/pull/14

We can re-open it if necessary for new reports.

**Comment by tfoote** [comment]
Awesome!
